allowBuilds:
  ai-elements-nuxt: true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  cbor-extract: true
  esbuild: true
  prisma: true
  vue-demi: true
patchedDependencies:
  ai-elements-nuxt@0.5.0: patches/ai-elements-nuxt@0.5.0.patch
